SELECT COUNT(*) FISH_COUNT,
       MAX(length) MAX_LENGTH,
       FISH_TYPE
FROM (
    SELECT FISH_TYPE,
           IFNULL(length, 10) LENGTH
    FROM FISH_INFO
) FISH_INFO
GROUP BY fish_type
HAVING AVG(length) >= 33
ORDER BY FISH_TYPE;