-- 코드를 입력하세요

## 1. NO JOIN
SELECT ugb.TITLE, 
       ugb.BOARD_ID, 
       ugr.REPLY_ID,
       ugr.WRITER_ID,
       ugr.CONTENTS,
       DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD ugb, USED_GOODS_REPLY ugr
WHERE ugb.BOARD_ID = ugr.BOARD_ID
AND ugb.CREATED_DATE LIKE '2022-10%'
ORDER BY CREATED_DATE, TITLE;

## 2. JOIN
SELECT ugb.TITLE,
       ugb.BOARD_ID,
       ugr.REPLY_ID,
       ugr.WRITER_ID,
       ugr.CONTENTS,
       DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD ugb
JOIN USED_GOODS_REPLY ugr
ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE ugb.CREATED_DATE LIKE '2022-10%'
ORDER BY CREATED_DATE, TITLE;